### PR TITLE
feat: disable code splitting / chunks

### PR DESCRIPTION
**Pull request by jordanmkoncz**
This pull request adds a new `--disable-chunks` flag, which causes the Webpack config to be modified so that code splitting / chunks are disabled. The result is that instead of having multiple different files generated (`bundle.js`, `main.chunk.js`, `0.chunk.js`, `1.chunk.js` etc.), only a single `bundle.js` file is generated.

For me, this made it easier to reference the generated JS file from within a Django template.

### CODE REVIEW

**Comment by jordanmkoncz** [comment]
Note: the configuration was taken from comments in https://github.com/facebook/create-react-app/issues/5306, and can also be seen in https://www.npmjs.com/package/react-app-rewire-disable-chunks.

**Comment by Nargonath** [comment]
I started updating the dependencies of the project on the develop branch. Would you mind basing your MR on develop instead of master please?

**Comment by jordanmkoncz** [comment]
@Nargonath sure thing, I think I've made the necessary change to the pull request?

**Comment by Nargonath** [comment]
Thanks for updating the PR. I don't have time right now to properly review your changes but I will do it ASAP. I'll let you know. 👍

**Pull request merged**
