### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by devxpy**
fix https://github.com/Nargonath/cra-build-watch/issues/1

Hope you don't mind me passing the code through a formatter

### CODE REVIEW

**Comment by Nargonath** [comment]
Thank you for your PR. The project is already configured with prettier and a precommit hook that runs it on the files you committed hence your local modifications should not pass through. I think I should add a CONTRIBUTING.md as well because for semantic-release there is a special commit format to follow so it can automatically handle version bumping. If you don't mind me asking, what actions did you take to commit? `git add` then `git commit`? I'm asking because there should have a routine check that prevent commit without the proper format.

**Comment by devxpy** [comment]
I used the online editor.

**Comment by Nargonath** [comment]
Thanks for the clarification. I'll need to make some fix in the commit message and reformat the source code then it will be good to go. :wink:

**Comment by Nargonath** [comment]
I thought as I merged your commit even though I updated it it would get this PR to `merged` state but it doesn't seem to have worked. I'll just close it then and `1.0.2` as been released.

**Pull request closed without merging**
